### ISSUE TITLE
Can't connect to G3 camera

### ISSUE THREAD

**Issue by loop2** [exsilium/docker-unifi-video#4] opened 2017-09-25 12:57 UTC
Hi! I followed your guide, the NVC is updated and also the camera is updated...
I have created the camera adoption token and compile it in the camera configuration page...
but when i manage it the camera it is disconnected or lost...
The date of camera is set correctly...

i notice that the ip addres of NVC is set automatically to 172.17.0.2 is not possible to se as new IP in my net?

thanks!

**Comment by exsilium** [comment] 2017-09-25 14:50
Hi @loop2 ! Which version you are pulling? v3.8.0?

With the guided setup the NVC reported IP will be the Docker internal IP, in your case the 172.170.0.2. It should be and has been thus far only cosmetic and shouldn’t impact functionality.

However, v3.8.0 introduced a new secure communication port so altough my own setup keeps on working, I haven’t provisioned new cameras.

If you did try v3.8.0 and are trying a new setup maybe you can pull v3.7.3 to see if that works for you. If it does, I can try to reproduce the issue on v3.8.0.

Let me know, thanks!

**Comment by loop2** [comment] 2017-09-25 14:58
Hi! Thanks for the support!
Finally i can use it... but i need to unmanage the camera and after that clik on manage, set the camera ip in 172.170.0.1 (instead the real ip), set the real ip of controller and the port 7442 in the camera setup...
The strange thing is that the setup is with this fake ip but the camera information show the real ip!
Now is fully working! thanks

**Comment by exsilium** [comment] 2017-09-27 09:27
Hi and thanks for the feedback. It seems it needs further testing on the newest version of the NVC. Thus far the internal IP hasn't blocked any update or provisioning processes, you just needed to do it once from the camera side.

It sounds like

1. You provisioned camera on an older firmware to v3.8.0
2. The provisioning worked or required a camera firmware upgrade right away?
3. Either case the cameras were unable to connect to the NVC because they were trying to connect to the Docker's internal IP.
4. You needed to unmanage the cameras and re-provision them from the camera side.

If nothing else then probably this scenario needs further documenting. In my case, my cameras were already provisioned prior to moving to v3.8.0. The camera firmware upgrade happened normally after the NVC version upgrade and all the cameras connected automatically after firmware upgrade.

It might be that the NVC reported IP is used in this case when the camera firmware upgrade happens during provisioning of the camera....

**Comment by exsilium** [comment] 2017-09-28 13:16
Closing as of now, let me know if there are further issues with your setup. Cheers! 🍻

**Closed as completed by exsilium** 2017-09-28 13:16 UTC
